Transform: AWS::Serverless-2016-10-31
Description: lambdas
Globals:
  Function:
    Timeout: 20
Resources:
  SamFirstEndpointhuwpxFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: SamFirstEndpointhuwpx/hello_world/
      Runtime: python3.9
      Handler: app.lambda_handler
      Description: SamFirstEndpointhuwpx
      Events:
          SamFirstEndpointhuwpx:
             Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
             Properties:
                Path: /SamFirstEndpointhuwpx
                Method: get
Outputs:
# ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
# Find out more about other implicit resources you can reference within SAM
# https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SamFirstEndpointhuwpxApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/SamFirstEndpointhuwpx/"
  SamFirstEndpointhuwpxFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt SamFirstEndpointhuwpxFunction.Arn
  SamFirstEndpointhuwpxFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt SamFirstEndpointhuwpxFunctionRole.Arn